### ISSUE TITLE
Summary - Feature Request

### ISSUE THREAD

**Issue by tbergen1** [JohnnyKrup/JammingProject#2]
### Criteria 1: Objective
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*:  Your objective is a great one.  Allowing users to listen to a preview of a track is a great UX element and will really improve the current Jamming app.  Nice work!

### Criteria 2: Background
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your background section is great!  It provides a detailed explanation of the pain point this feature is addressing.  You also gave a good summary of the overall functionality of the feature within the app.  Really awesome work!

### Criteria 3: Technical Design
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: You did a great job on your technical design section.  It is thorough and gives a good explanation of how you would modify the code to accommodate this new feature.  Great use of mocks as well to illustrate the feature with before/after shots.  Great work!

### Criteria 4: Caveats
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: You did a good job discussing some of the caveats that would come with a feature like this, specifically in dealing with the Spotify widget.  Nice work!

### Overall Score: 16/16
Overall, you did a good job with this feature request.  You chose a feature that would greatly improve the UX of the app and explained the necessity for this feature clearly and concisely.  You also did well in detailing the specific aspects of the technical implementation and what caveats you might encounter with your initial implementation.  Great work!

**Comment by JohnnyKrup** [comment]
Hi Tom,
Thanks a lot for the feedback and the kind words in your review.
Have a great day
Graziano
